const $=id=>document.getElementById(id),sb=supabase.createClient(GI_SUPABASE_URL,GI_SUPABASE_KEY);
let user,trainings=[],sheets=[],catalog=[],links=[],plans=[],sessions=[],logs=[],weekStart=startWeek(new Date()),currentDate,currentSheet,currentTraining,currentExercise,formSave;
const pad=n=>String(n).padStart(2,'0'),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),days=['dom','seg','ter','qua','qui','sex','sáb'];
function startWeek(d){let x=new Date(d);x.setHours(12,0,0,0);let n=x.getDay()||7;x.setDate(x.getDate()-n+1);return x}
function close(id){$(id).hidden=true;document.body.style.overflow=''}
function open(id){$(id).hidden=false;document.body.style.overflow='hidden'}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='trainings')renderTrainings();if(b.dataset.view==='catalog')renderCatalog()});
$('theme').onclick=()=>{let t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem('gi-theme',t)};
async function load(){let qs=[sb.from('gym_trainings').select('*').eq('user_id',user.id).order('created_at'),sb.from('gym_sheets').select('*').eq('user_id',user.id).order('sort_order'),sb.from('gym_exercise_catalog').select('*').eq('user_id',user.id).order('name'),sb.from('gym_sheet_exercises').select('*').eq('user_id',user.id).order('sort_order'),sb.from('gym_plans').select('*').eq('user_id',user.id),sb.from('gym_sessions').select('*').eq('user_id',user.id).order('session_date',{ascending:false}),sb.from('gym_session_exercises').select('*').eq('user_id',user.id).order('created_at',{ascending:false})],r=await Promise.all(qs);r.forEach(x=>x.error&&console.error(x.error));[trainings,sheets,catalog,links,plans,sessions,logs]=r.map(x=>x.data||[]);renderWeek();renderMetrics();if(document.getElementById('catalog')?.classList.contains('active'))renderCatalog()}
function renderMetrics(){let done=sessions.filter(s=>s.completed),now=new Date(),today=key(now),month=`${now.getFullYear()}-${pad(now.getMonth()+1)}`,md=done.filter(s=>s.session_date.startsWith(month)&&s.session_date<=today).length,elapsed=now.getDate();$('mTotal').textContent=new Set(done.map(s=>s.session_date)).size;$('mMonth').textContent=Math.round(md/elapsed*100)+'%';$('mMonthSub').textContent=`${md} dia${md===1?'':'s'} no mês`;$('mStreak').textContent=weekStreak(done);let prog=progression();$('mProgress').textContent=prog.total?`${prog.up}/${prog.total}`:'—';$('mProgressSub').textContent=prog.total?'exercícios com carga maior':'sem histórico suficiente'}
function weekStreak(done){let set=new Set(done.map(s=>key(startWeek(new Date(s.session_date+'T12:00:00'))))),w=startWeek(new Date()),n=0;while(set.has(key(w))){n++;w.setDate(w.getDate()-7)}return n}
function progression(){let by={};logs.filter(x=>x.completed&&x.weight!=null&&x.exercise_id).forEach(x=>(by[x.exercise_id]??=[]).push(x));let up=0,total=0;for(let a of Object.values(by)){a.sort((x,y)=>new Date(x.created_at)-new Date(y.created_at));if(a.length>1){total++;if(Number(a.at(-1).weight)>Number(a.at(-2).weight))up++}}return{up,total}}
function renderWeek(){let end=new Date(weekStart);end.setDate(end.getDate()+6);$('weekTitle').textContent=`${weekStart.getDate()}–${end.getDate()} ${end.toLocaleDateString('pt-BR',{month:'short'})}`;let html='';for(let i=0;i<7;i++){let d=new Date(weekStart);d.setDate(d.getDate()+i);let k=key(d),p=plans.find(x=>x.plan_date===k),sh=p&&sheets.find(x=>x.id===p.sheet_id),tr=sh&&trainings.find(x=>x.id===sh.training_id),ses=sessions.find(x=>x.session_date===k);html+=`<button class="day-card ${k===key(new Date())?'today':''} ${ses?.completed?'done':''}" data-day="${k}"><span class="dow">${days[d.getDay()]}</span><span class="date">${d.getDate()}</span>${sh?`<span class="workout">${ses?.completed?'<span class="check">✓ </span>':''}${esc(sh.name)}</span><span class="meta">${esc(tr?.name||'')}</span>`:'<span class="add-day">+</span><span class="meta">planejar</span>'}</button>`}$('weekGrid').innerHTML=html;$('weekGrid').querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>dayClick(b.dataset.day))}
function dayClick(k){currentDate=k;let p=plans.find(x=>x.plan_date===k);if(p){currentSheet=sheets.find(x=>x.id===p.sheet_id);openSession()}else openPicker()}
function openPicker(){$('pickerDate').textContent=new Date(currentDate+'T12:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});$('sheetOptions').innerHTML=sheets.length?sheets.map(s=>{let t=trainings.find(x=>x.id===s.training_id);return`<button class="option" data-pick="${s.id}"><strong>${esc(s.name)}</strong><small>${esc(t?.name||'')}</small></button>`}).join(''):'<div class="meta">Crie um Treino e uma Ficha primeiro.</div>';$('sheetOptions').querySelectorAll('[data-pick]').forEach(b=>b.onclick=async()=>{await sb.from('gym_plans').upsert({user_id:user.id,plan_date:currentDate,sheet_id:b.dataset.pick},{onConflict:'user_id,plan_date'});close('sheetPicker');await load();currentSheet=sheets.find(x=>x.id===b.dataset.pick);openSession()});open('sheetPicker')}
function sheetLinks(id){return links.filter(x=>x.sheet_id===id).sort((a,b)=>a.sort_order-b.sort_order)}
function openSession(){let ses=sessions.find(x=>x.session_date===currentDate),ls=ses?logs.filter(x=>x.session_id===ses.id).sort((a,b)=>a.sort_order-b.sort_order):sheetLinks(currentSheet.id).map(l=>{let e=catalog.find(x=>x.id===l.exercise_id),last=logs.find(x=>x.exercise_id===l.exercise_id&&x.weight!=null);return{exercise_id:l.exercise_id,exercise_name:e?.name||'',sets:l.sets,reps:l.reps,weight:last?.weight??'',completed:false,image_url:e?.image_url}});$('sessionDate').textContent=new Date(currentDate+'T12:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});$('sessionTitle').textContent=currentSheet.name;$('sessionNotes').value=ses?.notes||'';$('sessionExercises').innerHTML=ls.map(r=>{let e=catalog.find(x=>x.id===r.exercise_id),img=e?.image_url||r.image_url;return`<div class="exercise-row" data-ex="${r.exercise_id}" data-name="${esc(r.exercise_name)}" data-sets="${r.sets}" data-reps="${esc(r.reps)}"><div class="exercise-main"><input class="donebox" type="checkbox" ${r.completed?'checked':''}><div class="exercise-copy"><strong>${esc(r.exercise_name)}</strong><span>${r.sets} × ${esc(r.reps)}</span></div><label class="weight-wrap"><input class="weight" type="number" step="0.5" value="${r.weight??''}" placeholder="—"> kg</label></div>${img?`<button class="image-toggle">ver exercício</button><img class="exercise-image" src="${esc(img)}">`:''}</div>`}).join('');$('sessionExercises').querySelectorAll('.image-toggle').forEach(b=>b.onclick=()=>b.closest('.exercise-row').classList.toggle('image-open'));open('sessionModal')}
$('saveSession').onclick=async()=>{let ses=sessions.find(x=>x.session_date===currentDate),sid=ses?.id;if(!sid){let r=await sb.from('gym_sessions').insert({user_id:user.id,training_id:currentSheet.training_id,sheet_id:currentSheet.id,session_date:currentDate,completed:false,notes:$('sessionNotes').value}).select().single();if(r.error)return alert('Não consegui salvar.');sid=r.data.id}let rows=[...$('sessionExercises').querySelectorAll('.exercise-row')],payload=rows.map((r,i)=>({user_id:user.id,session_id:sid,exercise_id:r.dataset.ex||null,exercise_name:r.dataset.name,sets:Number(r.dataset.sets),reps:r.dataset.reps,weight:r.querySelector('.weight').value===''?null:Number(r.querySelector('.weight').value),completed:r.querySelector('.donebox').checked,sort_order:i,notes:null}));for(let p of payload)await sb.from('gym_session_exercises').upsert(p,{onConflict:'session_id,exercise_id'});let completed=payload.length>0&&payload.every(x=>x.completed);await sb.from('gym_sessions').update({completed,notes:$('sessionNotes').value,training_id:currentSheet.training_id,sheet_id:currentSheet.id,updated_at:new Date().toISOString()}).eq('id',sid).eq('user_id',user.id);close('sessionModal');await load()};
$('unplan').onclick=()=>{close('sessionModal');openPicker()};
function renderTrainings(){$('trainingList').innerHTML=trainings.length?trainings.map(t=>`<button class="program-card" data-training="${t.id}"><strong>${esc(t.name)}</strong><span class="meta">${sheets.filter(s=>s.training_id===t.id).length} ficha(s)</span></button>`).join(''):'<div class="meta">Nenhum treino criado.</div>';$('trainingList').querySelectorAll('[data-training]').forEach(b=>b.onclick=()=>openTraining(b.dataset.training))}
function openTraining(id){currentTraining=trainings.find(x=>x.id===id);$('trainingTitle').textContent=currentTraining.name;$('sheetList').innerHTML=sheets.filter(s=>s.training_id===id).map(s=>`<button class="sheet-card" data-sheet="${s.id}"><strong>${esc(s.name)}</strong><span class="meta">${sheetLinks(s.id).length} exercícios ›</span></button>`).join('')||'<div class="meta">Nenhuma ficha ainda.</div>';$('sheetList').querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>openSheet(b.dataset.sheet));open('trainingModal')}
function openSheet(id){currentSheet=sheets.find(x=>x.id===id);$('sheetTitle').textContent=currentSheet.name;$('sheetExerciseList').innerHTML=sheetLinks(id).map(l=>{let e=catalog.find(x=>x.id===l.exercise_id);return`<div class="sheet-card"><span>${esc(e?.name||'Exercício')}</span><span class="meta">${l.sets} × ${esc(l.reps)}</span></div>`}).join('')||'<div class="meta">Nenhum exercício nesta ficha.</div>';open('sheetModal')}
function exerciseStats(id){let xs=logs.filter(x=>x.exercise_id===id&&x.completed&&x.weight!=null).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(!xs.length)return{best:null,last:null,avg:null};let weights=xs.map(x=>Number(x.weight));return{best:Math.max(...weights),last:weights[0],avg:weights.reduce((a,b)=>a+b,0)/weights.length}}
function fmtKg(v){if(v==null||Number.isNaN(v))return'—';return`${Number.isInteger(v)?v:v.toFixed(1)} kg`}
function renderCatalog(){let q=$('exerciseSearch').value.toLowerCase(),items=catalog.filter(e=>[e.name,...(e.muscle_groups||[]),...(e.primary_muscles||[]),...(e.secondary_muscles||[])].join(' ').toLowerCase().includes(q));$('catalogList').innerHTML=items.map(e=>`<button class="catalog-card" data-exercise="${e.id}"><span class="catalog-thumb">${e.image_url?`<img src="${esc(e.image_url)}" alt="${esc(e.name)}">`:'⌁'}</span><span class="catalog-copy"><strong>${esc(e.name)}</strong><span class="tags">${[...(e.muscle_groups||[]),...(e.primary_muscles||[])].map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</span><span class="meta">${esc(e.equipment||'')}</span></span></button>`).join('')||'<div class="meta">Nenhum exercício cadastrado.</div>';$('catalogList').querySelectorAll('[data-exercise]').forEach(b=>b.onclick=()=>openExerciseDetail(b.dataset.exercise))}
$('exerciseSearch').oninput=renderCatalog;
function openExerciseDetail(id){currentExercise=catalog.find(x=>x.id===id);if(!currentExercise)return;$('exerciseDetailTitle').textContent=currentExercise.name;let tags=[...(currentExercise.muscle_groups||[]),...(currentExercise.primary_muscles||[]),...(currentExercise.secondary_muscles||[])];$('exerciseDetailTags').innerHTML=[...new Set(tags)].map(x=>`<span class="tag">${esc(x)}</span>`).join('');$('exerciseDetailEquipment').textContent=currentExercise.equipment||'';let wrap=$('exerciseDetailImageWrap');if(currentExercise.image_url){$('exerciseDetailImage').src=currentExercise.image_url;$('exerciseDetailImage').alt=currentExercise.name;wrap.hidden=false}else{wrap.hidden=true;$('exerciseDetailImage').removeAttribute('src')}let st=exerciseStats(id);$('exerciseBest').textContent=fmtKg(st.best);$('exerciseLast').textContent=fmtKg(st.last);$('exerciseAvg').textContent=fmtKg(st.avg);let notes=$('exerciseDetailNotes');if(currentExercise.notes){notes.textContent=currentExercise.notes;notes.hidden=false}else notes.hidden=true;open('exerciseModal')}
async function uploadExerciseImage(file){if(!file)return null;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){alert('Use uma imagem JPG, PNG ou WEBP.');return false}let ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',path=`${user.id}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`,up=await sb.storage.from('gym-exercises').upload(path,file,{upsert:false,contentType:file.type});if(up.error){console.error(up.error);alert('Não consegui enviar a foto.');return false}return sb.storage.from('gym-exercises').getPublicUrl(path).data.publicUrl}
function form(eyebrow,title,html,save){$('formEyebrow').textContent=eyebrow;$('formTitle').textContent=title;$('formBody').innerHTML=html;formSave=save;open('formModal')}
$('formSave').onclick=()=>formSave?.();
$('newTraining').onclick=()=>form('treino','Novo treino','<label class="field"><span>nome</span><input id="fName" placeholder="ex.: PPL"></label>',async()=>{let name=$('fName').value.trim();if(!name)return;await sb.from('gym_trainings').insert({user_id:user.id,name});close('formModal');await load();renderTrainings()});
$('newSheet').onclick=()=>form('ficha','Nova ficha','<label class="field"><span>nome</span><input id="fName" placeholder="ex.: A · Push"></label>',async()=>{let name=$('fName').value.trim();if(!name)return;await sb.from('gym_sheets').insert({user_id:user.id,training_id:currentTraining.id,name,sort_order:sheets.filter(x=>x.training_id===currentTraining.id).length});close('formModal');await load();openTraining(currentTraining.id)});
function exerciseFormHtml(e={}){return`<label class="field"><span>nome</span><input id="fName" value="${esc(e.name||'')}" placeholder="Leg Press 45°"></label><label class="field"><span>grupo(s) muscular(es)</span><input id="fGroups" value="${esc((e.muscle_groups||[]).join(', '))}" placeholder="Inferiores"></label><label class="field"><span>músculo(s) principal(is)</span><input id="fPrimary" value="${esc((e.primary_muscles||[]).join(', '))}" placeholder="Quadríceps, Glúteos"></label><label class="field"><span>músculo(s) secundário(s)</span><input id="fSecondary" value="${esc((e.secondary_muscles||[]).join(', '))}" placeholder="Posteriores de coxa"></label><label class="field"><span>equipamento</span><input id="fEquipment" value="${esc(e.equipment||'')}" placeholder="Leg press"></label><label class="field"><span>observação</span><textarea id="fNotes" placeholder="Opcional">${esc(e.notes||'')}</textarea></label><label class="field"><span>foto</span><input id="fImageFile" type="file" accept="image/jpeg,image/png,image/webp"></label>${e.image_url?'<small class="meta">Já existe uma foto. Envie outra apenas se quiser substituir.</small>':''}`}
function readExerciseFields(){const split=id=>$(id).value.split(',').map(x=>x.trim()).filter(Boolean);return{name:$('fName').value.trim(),muscle_groups:split('fGroups'),primary_muscles:split('fPrimary'),secondary_muscles:split('fSecondary'),equipment:$('fEquipment').value.trim()||null,notes:$('fNotes').value.trim()||null}}
$('newExercise').onclick=()=>form('exercício','Novo exercício',exerciseFormHtml(),async()=>{let data=readExerciseFields();if(!data.name)return;let img=await uploadExerciseImage($('fImageFile').files?.[0]);if(img===false)return;if(img)data.image_url=img;let r=await sb.from('gym_exercise_catalog').insert({user_id:user.id,...data});if(r.error){console.error(r.error);return alert('Não consegui criar o exercício.')}close('formModal');await load();renderCatalog()});
$('editExercise').onclick=()=>{if(!currentExercise)return;close('exerciseModal');form('exercício','Editar exercício',exerciseFormHtml(currentExercise),async()=>{let data=readExerciseFields();if(!data.name)return;let img=await uploadExerciseImage($('fImageFile').files?.[0]);if(img===false)return;if(img)data.image_url=img;let r=await sb.from('gym_exercise_catalog').update(data).eq('id',currentExercise.id).eq('user_id',user.id);if(r.error){console.error(r.error);return alert('Não consegui editar o exercício.')}close('formModal');await load();renderCatalog()})};
$('deleteExercise').onclick=async()=>{if(!currentExercise)return;if(!confirm(`Excluir ${currentExercise.name}? Ele também será removido das fichas, mas o histórico das sessões continua salvo.`))return;await sb.from('gym_sheet_exercises').delete().eq('exercise_id',currentExercise.id).eq('user_id',user.id);let r=await sb.from('gym_exercise_catalog').delete().eq('id',currentExercise.id).eq('user_id',user.id);if(r.error){console.error(r.error);return alert('Não consegui excluir o exercício.')}close('exerciseModal');currentExercise=null;await load();renderCatalog()};
$('addCatalogExercise').onclick=()=>form('ficha','Adicionar exercício',`<label class="field"><span>exercício</span><select id="fExercise">${catalog.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></label><label class="field"><span>séries</span><input id="fSets" type="number" value="3"></label><label class="field"><span>repetições</span><input id="fReps" value="10" placeholder="8–12"></label>`,async()=>{if(!$('fExercise').value)return;await sb.from('gym_sheet_exercises').insert({user_id:user.id,sheet_id:currentSheet.id,exercise_id:$('fExercise').value,name:catalog.find(e=>e.id===$('fExercise').value)?.name||'',sets:Number($('fSets').value)||3,reps:$('fReps').value||'10',sort_order:sheetLinks(currentSheet.id).length});close('formModal');await load();openSheet(currentSheet.id)});
$('prevWeek').onclick=()=>{weekStart.setDate(weekStart.getDate()-7);renderWeek()};$('nextWeek').onclick=()=>{weekStart.setDate(weekStart.getDate()+7);renderWeek()};$('todayWeek').onclick=()=>{weekStart=startWeek(new Date());renderWeek()};
async function init(){let{data:{session}}=await sb.auth.getSession();if(!session)return location.replace('/login.html?next=/academia/');user=session.user;await load();let s=document.createElement('script');s.src='../gi-nav.js';document.body.appendChild(s)}
init();